### PR TITLE
Feature/components analytics

### PR DESCRIPTION
**Pull request by helloimela**
Google analytics to monitor components.
How to use it:
<script src="/js/corporate-ui.js?monitoring=true"></script>
Monitoring parameter value:
- true (monitor components with corporate-ui track ID)
- custom GA track ID (UA-xxxx)

### CODE REVIEW

**Comment by scania-bootstrap** [comment]
I think it's best that @awinny reviews this as it is done in core C-UI.

Looking good though!

**Comment by awinny** [comment]
It seems a bit unnecessary to have the "same" set of command in all components.
Better place this in one file the will be used by all components.
For example in core.ts or in component.jade

**Comment by mmexvr** [comment]
Remember if you add a new dependency we need to add it on the server

**Comment by helloimela** [comment]
New dev dependencies: "@types/google.analytics": "0.0.39" - TypeScript definition for Google Analytics. Remember to add to AWS

**Comment by helloimela** [comment]
#286

**Pull request merged**
