### PR TITLE
Npm corporate ui

### PR DESCRIPTION
**Pull request by mohammed-softordi**
NPM package for Corporate-ui. The documentation works partially, I think you gyus will be able to fixe paths quickly than us. The file structure is not important for the npm-package, it's just a sugesting to make it easier for as to understand the framework

### CODE REVIEW

**Comment by finnlake** [comment]
What is happening with this pull request?

**Comment by scania-bootstrap** [comment]
We're working on it. 

/J

**Comment by mohammed-softordi** [comment]
Sounds good but our pull request already solves the problem with AWS.

**Comment by scania-bootstrap** [comment]
No Mohammed, it does not solve issues with Corporate UI ULRs and AWS way of handling them. Your branch contains a lot of + (plus) characters in the URLs and AWS does not follow http standards and do not allow them. That will make your branch simply crash when moved to AWS. As well as the current CDN solution. And right now, we have mixed zones (Intranet - Internet) zones with our current architecture (Cdn77 + Static Internal). That is highly production critic so that is of course our main issue right now. The suggestions in your branch is fine and well conducted, but it also has other implications that you do not fully understand.

We are therefore trying to solve them both at the same time. Be patient and use the CDN service for now and please spend the time merging pull requests critical to the FMP user experience.

We'll get to AWS and NPM farily soon but there is a lot to think of. It is not only you but 20-30 other applications using the Corporate UI.

/Jesper

**Comment by awinny** [comment]
As I see it this pull request is heavely connected to another pull request: #81.
And in that one we have also added support for relative paths and other things.
I sudjest that we close this request for now and spend some time together walking through #81 to see what more to add in that one.

**Pull request closed without merging**
